FROM jupyter/base-notebook:latest
RUN pip install --no-cache-dir mpld3==0.5.12 ipympl plotly numpy pandas matplotlib ipywidgets anywidget scikit-learn seaborn statsmodels yfinance mplfinance arch 'lightgbm[scikit-learn,pandas,plotting,polars,arrow]' xgboost-cpu sympy
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu